# platform :ios, ‘8.1’

target 'Museum' do
  use_frameworks!

  # Pods for Museum
	pod 'AlamofireObjectMapper', '~> 3.0'
    pod 'AlamofireImage', '~> 2.0'

  target 'MuseumTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MuseumUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
